import { PromptTemplateDefinition } from "./types.js";

import VARIABLE_OUTPUT_FORMAT_MARKDOWN_DOC from "./VARIABLE_OUTPUT_FORMAT_MARKDOWN_DOC.js";
import VARIABLE_FORMATTING_REQUIREMENTS from "./VARIABLE_FORMATTING_REQUIREMENTS.js";
import VARIABLE_ADDITIONAL_INSTRUCTIONS from "./VARIABLE_ADDITIONAL_INSTRUCTIONS.js";

export const PROMPT_VARIABLES: Record<string, PromptTemplateDefinition> = {
  VARIABLE_OUTPUT_FORMAT_MARKDOWN_DOC,
  VARIABLE_FORMATTING_REQUIREMENTS,
  VARIABLE_ADDITIONAL_INSTRUCTIONS,
};

export type PromptVariable = keyof typeof PROMPT_VARIABLES;
