# Configuration file for Mega-Linter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
DEFAULT_BRANCH: main # Usually master or main
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - EDITORCONFIG
DISABLE_LINTERS:
  - JSON_JSONLINT
  - TYPESCRIPT_STANDARD
GITHUB_STATUS_REPORTER: false
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
YAML_V8R_DISABLE_ERRORS: true
FILTER_REGEX_EXCLUDE: "(vscode|defaults|docs)"
TYPESCRIPT_DEFAULT_STYLE: prettier
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3007 --ignore DL3016 --ignore DL3018 --ignore DL4006"
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
