# Docker image to run sfdx-hardis

FROM python:3.12.10-slim

LABEL maintainer="Nicolas VUILLAMY <nicolas.vuillamy@cloudity.com>"

# Update package list and install required packages
RUN apt-get update && apt-get install -y --no-install-recommends \
            coreutils \
            git \
            bash \
            curl \
            gnupg \
            lsb-release \
            ca-certificates \
            # Required for docker
            docker.io \
            # Required for puppeteer
            chromium-browser \
            fonts-liberation \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libatspi2.0-0 \
            libcups2 \
            libdbus-1-3 \
            libdrm2 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libx11-6 \
            libxcomposite1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxkbcommon0 \
            libxrandr2 \
            xdg-utils && \
    # Install Node.js
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs && \
    # Clean up
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Do not use puppeteer embedded chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
ENV CHROMIUM_PATH="/usr/bin/chromium-browser"
ENV PUPPETEER_EXECUTABLE_PATH="${CHROMIUM_PATH}"

# Add node packages to path
ENV PATH="/node_modules/.bin:${PATH}"

ARG SFDX_CLI_VERSION=latest
ARG SFDX_HARDIS_VERSION=latest

# Install npm packages +install sfdx plugins & display versions
RUN npm install --no-cache yarn -g && \
    npm install --no-cache @salesforce/cli@${SFDX_CLI_VERSION} -g && \
    sf plugins install @salesforce/plugin-packaging && \
    sf plugins install @salesforce/plugin-deploy-retrieve && \
    echo 'y' | sf plugins install sfdx-hardis@${SFDX_HARDIS_VERSION} && \
    echo 'y' | sf plugins install sfdmu && \
    echo 'y' | sf plugins install sfdx-git-delta && \
    echo 'y' | sf plugins install texei-sfdx-plugin && \
    sf version --verbose --json && \
    rm -rf /root/.npm/_cacache

ENV MERMAID_MODES="docker"

# Workaround for https://github.com/forcedotcom/salesforcedx-apex/issues/213
COPY ref/workarounds/dateUtil.js /usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/utils/dateUtil.js
COPY ref/workarounds/junitReporter.js /usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/apex-node/lib/src/reporters/junitReporter.js
