# Add your major branches names here
# If you do, also add SFDX_CLIENT_ID / KEY variables in job step "Login & Simulate Deployment" below
on:
  pull_request:
    branches:
      - main
      - preprod
      - uat
      - integration

name: Simulate Deployment (sfdx-hardis)
jobs:
  check_deployment:
    runs-on: ubuntu-latest
    name: Simulate Deployment to Major Org
    steps:
    # Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Faster code checkout fetching only latest commit
    # Setup node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    # SFDX & plugins
    - name: Install SFDX and plugins
      run: |
        npm install --no-cache @salesforce/cli --global
        sf plugins install @salesforce/plugin-packaging
        echo 'y' | sfdx plugins:install sfdx-hardis
        echo 'y' | sfdx plugins:install sfdx-essentials
        echo 'y' | sfdx plugins:install sfdx-git-delta
        sf version --verbose --json
    # Login & check deploy with test classes & code coverage
    - name: Login & Simulate deployment
      env:
        SFDX_CLIENT_ID_INTEGRATION: ${{ secrets.SFDX_CLIENT_ID_INTEGRATION}}
        SFDX_CLIENT_KEY_INTEGRATION: ${{ secrets.SFDX_CLIENT_KEY_INTEGRATION}}
        SFDX_CLIENT_ID_UAT: ${{ secrets.SFDX_CLIENT_ID_UAT}}
        SFDX_CLIENT_KEY_UAT: ${{ secrets.SFDX_CLIENT_KEY_UAT}}
        SFDX_CLIENT_ID_PREPROD: ${{ secrets.SFDX_CLIENT_ID_PREPROD}}
        SFDX_CLIENT_KEY_PREPROD: ${{ secrets.SFDX_CLIENT_KEY_PREPROD}}
        SFDX_CLIENT_ID_MAIN: ${{ secrets.SFDX_CLIENT_ID_MAIN}}
        SFDX_CLIENT_KEY_MAIN: ${{ secrets.SFDX_CLIENT_KEY_MAIN}}
        SFDX_DEPLOY_WAIT_MINUTES: 120 # Override if necessary
        SFDX_TEST_WAIT_MINUTES: 120 # Override if necessary
        CI_COMMIT_REF_NAME: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
        ORG_ALIAS: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
        CONFIG_BRANCH: ${{ github.event.pull_request.base.ref }} # Defines the target branch of the PR
      run: |
        echo "Simulate SFDX deployment using Hardis against \"$CONFIG_BRANCH\""
        sfdx hardis:auth:login
        sfdx hardis:project:deploy:sources:dx --check
