{
 "title": "06 - Technical Debt",
 "description": "Technical debt burn-down: unused metadata, inactive automations, code coverage evolution.",
 "tags": [
  "sfdx-hardis-v2",
  "sfdx-hardis"
 ],
 "time": { "from": "now-180d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prom", "label": "Prometheus datasource", "query": "prometheus" },
   { "name": "ds_loki", "label": "Loki datasource", "query": "loki" },
   {
    "name": "org",
    "label": "Salesforce Org",
    "query": {
     "query": "label_values({source=\"sfdx-hardis\"}, orgIdentifier)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current debt (click a number for details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Unused metadata",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(MetadatasNotUsed_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Unused Apex classes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(unusedApexClasses_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Inactive Flows & VRs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(InactiveMetadatas_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Items without description",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(MetadatasWithoutDescription_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Items without access",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(ElementsWithNoProfileOrPermissionSetAccess_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Deprecated Apex",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(deprecatedApexTotal_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  { "title": "Burn-down", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Technical debt evolution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(MetadatasNotUsed_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[1d]))",
     "legendFormat": "Unused metadata"
    },
    {
     "expr": "max by (orgIdentifier) (last_over_time(unusedApexClasses_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[1d]))",
     "legendFormat": "Unused Apex classes"
    },
    {
     "expr": "max by (orgIdentifier) (last_over_time(InactiveMetadatas_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[1d]))",
     "legendFormat": "Inactive Flows & VRs"
    },
    {
     "expr": "max by (orgIdentifier) (last_over_time(MetadatasWithoutDescription_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[1d]))",
     "legendFormat": "Without description"
    },
    {
     "expr": "max by (orgIdentifier) (last_over_time(ElementsWithNoProfileOrPermissionSetAccess_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[1d]))",
     "legendFormat": "Without access"
    }
   ]
  },
  { "title": "Apex code coverage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Current coverage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(ApexTestsCodeCoverage_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Coverage evolution (75% threshold)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(ApexTestsCodeCoverage_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[1d]))",
     "legendFormat": "Coverage"
    }
   ]
  },
  {
   "title": "Permission sets (click a number for details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Underused permission sets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(UnderusedPermissionSets_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Zero-user permission sets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(ZeroUserPermissionSets_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Zero-user permission set groups",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(ZeroUserPermissionSetGroups_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Unused PS licenses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(UnusedPermissionSetLicenses_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  }
 ]
}