{
 "title": "02 - Reliability (Apex & Flow errors)",
 "description": "Apex and Flow error trends, top failing automations and impacted users for one org.",
 "tags": [
  "sfdx-hardis-v2",
  "sfdx-hardis"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prom", "label": "Prometheus datasource", "query": "prometheus" },
   { "name": "ds_loki", "label": "Loki datasource", "query": "loki" },
   {
    "name": "org",
    "label": "Salesforce Org",
    "query": {
     "query": "label_values({source=\"sfdx-hardis\"}, orgIdentifier)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Error trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors per day with 7d average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(ApexErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[1d]))",
     "legendFormat": "Apex errors"
    },
    {
     "expr": "max by (orgIdentifier) (last_over_time(FlowErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[1d]))",
     "legendFormat": "Flow errors"
    },
    {
     "expr": "max by (orgIdentifier) (avg_over_time(ApexErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[7d]))",
     "legendFormat": "Apex 7d avg"
    },
    {
     "expr": "max by (orgIdentifier) (avg_over_time(FlowErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[7d]))",
     "legendFormat": "Flow 7d avg"
    }
   ]
  },
  {
   "title": "Errors this week vs last week",
   "type": "stat",
   "description": "Positive = more errors than the previous 7 days.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(sum_over_time(ApexErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[7d])) or vector(0)) + (sum(sum_over_time(FlowErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[7d])) or vector(0))) - ((sum(sum_over_time(ApexErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[7d] offset 7d)) or vector(0)) + (sum(sum_over_time(FlowErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[7d] offset 7d)) or vector(0)))"
    }
   ]
  },
  {
   "title": "Averages (click a number for details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Apex avg/day (7d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (avg_over_time(ApexErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[7d]))"
    }
   ]
  },
  {
   "title": "Apex avg/day (30d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (avg_over_time(ApexErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[30d]))"
    }
   ]
  },
  {
   "title": "Apex max/day (30d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (max_over_time(ApexErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[30d]))"
    }
   ]
  },
  {
   "title": "Flow avg/day (7d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (avg_over_time(FlowErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[7d]))"
    }
   ]
  },
  {
   "title": "Flow avg/day (30d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (avg_over_time(FlowErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[30d]))"
    }
   ]
  },
  {
   "title": "Flow max/day (30d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (max_over_time(FlowErrors_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[30d]))"
    }
   ]
  },
  {
   "title": "Impact (click a number for details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Users impacted by Apex errors",
   "type": "stat",
   "description": "Distinct users hit by Apex errors in the last collection window. Requires a recent sfdx-hardis version on the monitoring pipeline (empty until then).",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(ApexErrorsImpactedUsers_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Users impacted by Flow errors",
   "type": "stat",
   "description": "Requires a recent sfdx-hardis version on the monitoring pipeline (empty until then).",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(FlowErrorsImpactedUsers_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Top failing Flow (errors)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(TopFailingFlowCount_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Top failing Apex (errors)",
   "type": "stat",
   "description": "Requires a recent sfdx-hardis version on the monitoring pipeline (empty until then).",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (orgIdentifier) (last_over_time(TopFailingApexCount_metric{source=\"sfdx-hardis\", orgIdentifier=\"$org\"}[2d]))"
    }
   ]
  },
  {
   "title": "Top failing automations (latest run)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Top failing Flows",
   "type": "table",
   "description": "Requires a recent sfdx-hardis version on the monitoring pipeline (empty until then).",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{source=\"sfdx-hardis\", type=\"FLOW_ERROR\", orgIdentifier=\"$org\"} |= ``",
     "direction": "backward",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Top failing Flow steps",
   "type": "table",
   "description": "Requires a recent sfdx-hardis version on the monitoring pipeline (empty until then).",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "{source=\"sfdx-hardis\", type=\"FLOW_ERROR\", orgIdentifier=\"$org\"} |= ``",
     "direction": "backward",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Top failing Apex",
   "type": "table",
   "description": "Requires a recent sfdx-hardis version on the monitoring pipeline (empty until then).",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "{source=\"sfdx-hardis\", type=\"APEX_ERROR\", orgIdentifier=\"$org\"} |= ``",
     "direction": "backward",
     "maxLines": 1
    }
   ]
  },
  { "title": "Latest error details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Latest Apex errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{source=\"sfdx-hardis\", type=\"APEX_ERROR\", orgIdentifier=\"$org\"} |= ``",
     "direction": "backward",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Latest Flow errors",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "{source=\"sfdx-hardis\", type=\"FLOW_ERROR\", orgIdentifier=\"$org\"} |= ``",
     "direction": "backward",
     "maxLines": 1
    }
   ]
  }
 ]
}