/* jscpd:ignore-start */
import { SfCommand, Flags, requiredOrgFlagWithDeprecations } from '@salesforce/sf-plugins-core';
import { Messages } from '@salesforce/core';
import { AnyJson } from '@salesforce/ts-types';
import c from 'chalk';
import fs from '../../../../common/utils/fsUtils.js';
import * as path from 'path';
import { execCommand, uxLog } from '../../../../common/utils/index.js';
import { uxLogTableWithReport } from '../../../../common/utils/filesUtils.js';
import { CONSTANTS, getConfig, getCurrentI18nLocale, getEnvVar } from '../../../../config/index.js';
import { t } from '../../../../common/utils/i18n.js';
import { AiProvider } from '../../../../common/aiProvider/index.js';
import { collectMonitoringNotifications } from '../../../../common/notifProvider/monitoringNotifWriter.js';
import { NotifProvider } from '../../../../common/notifProvider/index.js';
import { generateMonitoringAiSummary } from '../../../../common/utils/monitoringSummary.js';
import { generateMonitoringPptxReport } from '../../../../common/utils/monitoringPptxReport.js';
import { WebSocketClient } from '../../../../common/websocketClient.js';
import { setConnectionVariables } from '../../../../common/utils/orgUtils.js';
import { resolveMonitoringCommands, shouldRunCommandNow } from '../../../../common/notifProvider/notificationConfig.js';
import { getTitleI18nKey, monitoringCommandsDefault } from '../../../../common/monitoring/monitoringDefaults.js';
import { computeHealthScore } from '../../../../common/monitoring/healthScore.js';
import type { MonitoringCommandEntry } from '../../../../common/notifProvider/types.js';

Messages.importMessagesDirectoryFromMetaUrl(import.meta.url);
const messages = Messages.loadMessages('sfdx-hardis', 'org');

export default class MonitorAll extends SfCommand<any> {
  public static title = 'Monitor org';

  // Re-export the shared default list for plugin / extension consumers that historically read this static property.
  public static monitoringCommandsDefault: MonitoringCommandEntry[] = monitoringCommandsDefault;

  public static description = `Monitor org, generate reports and sends notifications

## Command Behavior

**Runs all monitoring commands on a Salesforce org, generates reports, and sends notifications.**

Key functionalities:

- **Monitoring commands:** Runs a [default list of monitoring commands](${CONSTANTS.DOC_URL_ROOT}/salesforce-monitoring-home/#monitoring-commands) (or custom ones defined in \`.sfdx-hardis.yml\`), each producing individual notifications.
- **Non-interactive execution:** Every monitoring sub-command is executed with \`--agent\`, enforcing non-interactive behavior (no user prompts).
- **Consolidated summary notification:** After all commands complete, a \`MONITORING_SUMMARY\` notification is always sent. It carries the run status metrics and doubles as a daily heartbeat for observability backends (Grafana freshness panels and "silent org" alerts rely on it).
- **AI-powered summary:** When an AI provider is configured, the summary notification text is a consolidated **executive summary** generated by AI from all monitoring notifications.
- **Weekly org health score:** On weekly runs, an **org health score** (0-100) is computed from the collected notifications (reliability, limits, security, tests, technical debt sub-scores) and sent as metrics with the summary notification, ready to be charted in [Grafana dashboards](${CONSTANTS.DOC_URL_ROOT}/salesforce-monitoring-grafana-v2/).
- **Weekly PPTX report:** On weekly runs (Saturday by default, or when \`--force-all\` is passed, or when env var \`MONITORING_IGNORE_FREQUENCY=true\` is set), a **PowerPoint report** can be generated by a [coding agent](${CONSTANTS.DOC_URL_ROOT}/salesforce-deployment-agent-autofix/) (Claude, Codex, Gemini, or Copilot) and attached to the summary notification.
- **Report generation toggle (disabled by default):** Enable coding-agent PPTX generation with \`codingAgentGenerateReports: true\` or env var \`SFDX_HARDIS_CODING_AGENT_GENERATE_REPORTS=true\`. Requires \`codingAgent\` to be configured.
- **Frequency control:** Commands can run \`daily\`, \`weekly\`, \`biweekly\`, \`monthly\`, or \`off\`. Use \`frequencyDay\` (monday..sunday) to pick the firing day for weekly/biweekly, and \`frequencyDayOfMonth\` (1-31) for monthly. Use \`--force-all\` (or env var \`MONITORING_IGNORE_FREQUENCY=true\`) to force all commands to run regardless of their configured frequency.
- **Cadence traceability:** The run starts with a line stating today's date and whether frequency gating is active, or disabled and by which of \`--force-all\` / \`MONITORING_IGNORE_FREQUENCY\`. The end-of-run summary lists every configured command with its frequency and its status, including the ones that were skipped (\`skipped\`) or turned off through \`monitoringDisable\` (\`disabled\`).
- **Per-channel notification routing:** Each entry accepts a \`notifications\` block with severity thresholds per channel (\`messaging\`, \`email\`, \`api\`). User entries are merged by \`key\` onto the built-in defaults, so you can override only the fields you need.

This command is part of [sfdx-hardis Monitoring](${CONSTANTS.DOC_URL_ROOT}/salesforce-monitoring-home/).

<details markdown="1">
<summary>Technical explanations</summary>

The command runs each monitoring sub-command sequentially with \`--agent\` and collects exit codes.

Each sub-command's notifications are written to temporary JSON files via \`MONITORING_NOTIF_OUTPUT_DIR\`. After all commands complete, the notifications are collected and a consolidated \`MONITORING_SUMMARY\` notification is always sent, with run status metrics (\`NotificationCount\`, \`CommandsFailed\`, \`ChannelsFailed\`). Without an AI summary it is sent with severity \`log\` (observability backends only); with one, severity \`info\` (also delivered to messaging/email channels by default). When an AI provider is available (\`AiProvider.isAiAvailable()\`), the notification text is an AI summary generated using the \`PROMPT_MONITORING_SUMMARY\` template.

On weekly runs (Saturday or \`--force-all\`), an org health score is computed from the collected notifications (pure computation, no extra org call) and added to the summary metrics: \`HealthScore\` plus \`HealthScoreReliability\`, \`HealthScoreLimits\`, \`HealthScoreSecurity\`, \`HealthScoreTests\`, \`HealthScoreDebt\`. Sub-scores whose source command did not run are omitted; a backup failure caps the global score at 50.

On weekly runs, a PPTX report is generated by invoking a coding agent CLI with the \`PROMPT_MONITORING_PPTX_REPORT\` template. The agent writes a Node.js script using \`pptxgenjs\` to produce a structured 7-slide PowerPoint presentation. The PPTX file is attached to the summary notification.

Both prompt templates can be overridden by placing files in \`config/prompt-templates/\`.
</details>

You can enable coding-agent PPTX generation by defining **codingAgentGenerateReports: true** in \`.sfdx-hardis.yml\` or by setting env var **SFDX_HARDIS_CODING_AGENT_GENERATE_REPORTS=true**.

A [default list of monitoring commands](${CONSTANTS.DOC_URL_ROOT}/salesforce-monitoring-home/#monitoring-commands) is used. You can extend or override it via the **monitoringCommands** property in your .sfdx-hardis.yml file. User entries are **merged by key** onto the built-in defaults, so you can override one field (e.g. \`frequency\`) without redefining the whole entry. New keys are appended as custom commands. Set \`frequency: off\` on an entry to skip it entirely.

Example (override built-in defaults + add a custom command + tune routing):

\`\`\`yaml
monitoringCommands:
  - key: AUDIT_TRAIL
    frequency: weekly
    frequencyDay: monday
    notifications:
      messaging: warning
      email:
        threshold: error
        recipients:
          - security@company.com
        replaceRecipients: true
      api: log
  - key: LICENSES
    frequency: monthly
    frequencyDayOfMonth: 1
  - key: ORG_LIMITS
    frequency: off
  - key: MY_CUSTOM_REPORT
    title: My Custom command
    command: sf my:custom:command
    frequency: biweekly
\`\`\`

You can force a run of all commands regardless of their configured frequency by passing \`--force-all\` (or by setting env var \`MONITORING_IGNORE_FREQUENCY=true\`).

The default list of commands is the following:

${this.getDefaultCommandsMarkdown()}

`;

  public static examples = [
    '$ sf hardis:org:monitor:all',
    '$ sf hardis:org:monitor:all --target-org myorg@example.com',
    '$ sf hardis:org:monitor:all --force-all --agent',
    '$ sf hardis:org:monitor:all --target-org myorg@example.com --debug',
  ];

  public static flags: any = {
    agent: Flags.boolean({
      default: false,
      description: 'Run in non-interactive mode for agents and automation',
    }),
    'force-all': Flags.boolean({
      default: false,
      description: 'Force all monitoring commands to run, regardless of their configured frequency',
    }),
    debug: Flags.boolean({
      char: 'd',
      default: false,
      description: messages.getMessage('debugMode'),
    }),
    websocket: Flags.string({
      description: messages.getMessage('websocket'),
    }),
    skipauth: Flags.boolean({
      description: 'Skip authentication check when a default username is required',
    }),
    'target-org': requiredOrgFlagWithDeprecations,
  };

  // Set this to true if your command requires a project workspace; 'requiresProject' is false by default
  public static requiresProject = true;

  // Trigger notification(s) to MsTeams channel
  protected static triggerNotification = true;

  protected debugMode = false;

  /* jscpd:ignore-end */

  public static getDefaultCommandsMarkdown() {
    const mdLines = [
      "| Key | Description | Command | Frequency |",
      "| :---: | :---- | :---- | :-----: |",

    ];
    for (const cmd of MonitorAll.monitoringCommandsDefault) {
      if (!cmd.command) {
        continue;
      }
      const commandDocUrl = `${CONSTANTS.DOC_URL_ROOT}/${cmd.command.split(" ")[1].replaceAll(":", "/")}`;
      const title = cmd.title ?? t(getTitleI18nKey(cmd.key));
      mdLines.push(`| [${cmd.key}](${commandDocUrl}) | ${title} | [${cmd.command}](${commandDocUrl}) | ${cmd.frequency} |`);
    }
    return mdLines.join("\n");
  }

  private static formatDuration(ms: number): string {
    if (ms < 1000) {
      return `${Math.round(ms)}ms`;
    }
    const seconds = Math.floor(ms / 1000);
    const remainder = ms % 1000;
    if (seconds < 60) {
      return remainder > 0 ? `${seconds}.${Math.floor(remainder / 100)}s` : `${seconds}s`;
    }
    const minutes = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${minutes}m ${secs}s`;
  }

  public async run(): Promise<AnyJson> {
    const { flags } = await this.parse(MonitorAll);
    this.debugMode = flags.debug || false;
    // Keep the source of the override: a run that ignores frequencies looks exactly like a broken
    // cadence in the notification channels, so the log must say which one turned the gating off.
    const forceAllSource = flags['force-all']
      ? '--force-all'
      : getEnvVar('MONITORING_IGNORE_FREQUENCY') === 'true'
        ? 'MONITORING_IGNORE_FREQUENCY=true'
        : null;
    const forceAll = forceAllSource !== null;

    const orgUrl = flags['target-org'].getConnection().instanceUrl;
    await setConnectionVariables(flags['target-org']?.getConnection(), true);// Required for some notifications providers like Email

    uxLog(
      "action",
      this,
      c.cyan(t('runningMonitoringScriptsForOrg', { orgAlias: c.bold(orgUrl) }))
    );

    // Cadence banner: without it, a forced run leaves no trace at all in the CI log, and the
    // per-command skip lines below are grey noise in a several-thousand-line output.
    const cadenceDate = new Date().toLocaleDateString(getCurrentI18nLocale(), {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    if (forceAllSource) {
      uxLog("warning", this, c.yellow(t('monitoringFrequencyGatingForced', { source: c.bold(forceAllSource), date: c.bold(cadenceDate) })));
    } else {
      uxLog("action", this, c.cyan(t('monitoringFrequencyGatingActive', { date: c.bold(cadenceDate) })));
    }

    const config = await getConfig('user');
    const commands = resolveMonitoringCommands(MonitorAll.monitoringCommandsDefault, config.monitoringCommands);
    const monitoringDisable =
      config.monitoringDisable ?? (process.env?.MONITORING_DISABLE ? process.env.MONITORING_DISABLE.split(',') : []);
    const codingAgentGenerateReports =
      getEnvVar('SFDX_HARDIS_CODING_AGENT_GENERATE_REPORTS') === 'true' ? true :
        getEnvVar('SFDX_HARDIS_CODING_AGENT_GENERATE_REPORTS') === 'false' ? false :
          config.codingAgentGenerateReports ?? false;

    // Check if AI is available for notification collection and summary
    const aiAvailable = await AiProvider.isAiAvailable();
    const notifDir = path.resolve('hardis-report', 'monitoring-notifs');
    // Always set up notification directory to collect sub-command notifications
    // (needed for PPTX report generation, regardless of AI availability)
    await fs.ensureDir(notifDir);
    // Remove any stale notification files from previous runs
    await fs.emptyDir(notifDir);
    process.env.MONITORING_NOTIF_OUTPUT_DIR = notifDir;

    let success = true;
    const commandsSummary: any[] = [];
    for (const command of commands) {
      if (!command.command) {
        // Routing-only entry (no command to run) -- skip silently
        continue;
      }
      const commandFrequency = command.frequency ?? 'daily';
      if (monitoringDisable.includes(command.key)) {
        uxLog("log", this, c.grey(t('skippedCommandAccordingToCustomConfiguration', { command: c.bold(command.key) })));
        commandsSummary.push({
          title: command.title ?? t(getTitleI18nKey(command.key)),
          status: 'disabled',
          frequency: commandFrequency,
          command: command.command,
          duration: '-',
        });
        continue;
      }
      if (!forceAll) {
        const evaluation = shouldRunCommandNow(command);
        if (!evaluation.shouldRun && evaluation.reasonKey) {
          uxLog("log", this, c.grey(t(evaluation.reasonKey, { command: c.bold(command.key) })));
          commandsSummary.push({
            title: command.title ?? t(getTitleI18nKey(command.key)),
            status: 'skipped',
            frequency: commandFrequency,
            command: command.command,
            duration: '-',
          });
          continue;
        }
      }
      // Run command
      let commandStr = /(^|\s)--agent(\s|$)/.test(command.command)
        ? command.command
        : `${command.command} --agent`;
      if (/^sf hardis/.test(commandStr) && !/(^|\s)--skipauth(\s|$)/.test(commandStr)) {
        commandStr = `${commandStr} --skipauth`;
      }
      const commandTitle = command.title ?? t(getTitleI18nKey(command.key));
      uxLog("action", this, c.cyan(t('runningMonitoringCommandKey', { command: c.bold(commandTitle), command1: c.bold(command.key) })));
      const startTime = Date.now();
      try {
        const execCommandResult = await execCommand(commandStr, this, { fail: false, output: true });
        const duration = Date.now() - startTime;
        if (execCommandResult.status === 0) {
          uxLog("success", this, c.green(t('commandHasBeenRunSuccessfully', { command: c.bold(commandTitle) })));
        } else {
          success = false;
          uxLog("warning", this, c.yellow(t('commandHasFailed', { command: c.bold(commandTitle) })));
        }
        commandsSummary.push({
          title: commandTitle,
          status: execCommandResult.status === 0 ? 'success' : 'failure',
          frequency: commandFrequency,
          command: command.command,
          duration: MonitorAll.formatDuration(duration),
        });
      } catch (e) {
        // Handle unexpected failure
        const duration = Date.now() - startTime;
        success = false;
        uxLog("warning", this, c.yellow(t('commandHasFailed2', { command: c.bold(commandTitle), as: (e as Error).message })));
        commandsSummary.push({
          title: commandTitle,
          status: 'error',
          frequency: commandFrequency,
          command: command.command,
          duration: MonitorAll.formatDuration(duration),
        });
      }
    }

    uxLog("action", this, c.cyan(t('summaryOfMonitoringScripts')));
    // Row count is data-driven (one row per configured command, skipped ones included), so it goes
    // past what the VS Code UI renders: uxLogTableWithReport writes a CSV when that happens.
    await uxLogTableWithReport(this, commandsSummary, ['title', 'status', 'frequency', 'command', 'duration'], {
      fileNamePrefix: 'monitoring-commands',
      fileTitle: 'Monitoring commands run summary',
    });
    uxLog("log", this, c.grey(t('youCanCheckDetailsInReportsIn')));

    uxLog(
      "warning",
      this,
      c.yellow(t('toKnowMoreAboutMonitoring'))
    );

    // Generate AI-powered summary and optional PPTX report
    // Collect monitoring notifications from sub-commands
    let notifications: any[] = [];
    try {
      notifications = await collectMonitoringNotifications(notifDir);
    } catch (e) {
      uxLog("warning", this, c.yellow(t('monitoringAiSummaryFailed', { message: (e as Error).message })));
    }

    // Generate AI summary if available and there are notifications
    let aiSummary: string | null = null;
    if (aiAvailable && notifications.length > 0) {
      try {
        aiSummary = await generateMonitoringAiSummary(notifications, orgUrl);
      } catch (summaryErr) {
        uxLog("warning", this, c.yellow(t('monitoringAiSummaryFailed', { message: (summaryErr as Error).message })));
      }
    }

    // Generate PPTX on the weekly cadence using a coding agent - regardless of AI availability
    const isWeekly = new Date().getDay() === 6 || forceAll;
    if (isWeekly && codingAgentGenerateReports) {
      // codingAgent PPTX generation still anchored on the original Saturday cadence (or --force-all);
      // per-command frequency changes (biweekly/monthly) only affect command execution, not this report.
      try {
        const reportDir = path.resolve(config.reportDirectory || 'hardis-report');
        await fs.ensureDir(reportDir);
        const pptxPath = await generateMonitoringPptxReport(notifications, aiSummary, orgUrl, reportDir);
        if (pptxPath) {
          uxLog("success", this, c.green(t('monitoringPptxReportGenerated', { path: pptxPath })));
          WebSocketClient.sendReportFileMessage(pptxPath, t('monitoringPptxReport', { path: pptxPath }), "report");
        }
      } catch (pptxErr) {
        uxLog("warning", this, c.yellow(t('monitoringPptxReportFailed', { message: (pptxErr as Error).message })));
      }
    }

    // Compute org health score on weekly runs only: the weekly batch provides the full
    // input set (daily runs miss weekly/monthly indicators). Pure computation on already
    // collected notifications: no command re-run, no extra org call.
    const summaryMetrics: Record<string, number> = {
      NotificationCount: notifications.length,
      // Only commands that actually ran and went wrong: the summary also carries skipped
      // (frequency) and disabled (monitoringDisable) rows, which are not failures
      CommandsFailed: commandsSummary.filter((cmd) => ['failure', 'error'].includes(cmd.status)).length,
      // Channel send failures are warnings (they no longer fail commands), so this metric
      // is the way to detect them in Grafana: alert on ChannelsFailed > 0
      ChannelsFailed: notifications.reduce((sum, notif) => sum + (notif.failedChannels?.length || 0), 0),
    };
    let healthScoreDetails: string[] | null = null;
    if (isWeekly && notifications.length > 0) {
      const healthScore = computeHealthScore(notifications);
      if (healthScore) {
        summaryMetrics.HealthScore = healthScore.score;
        const subScoreMetricNames: Record<string, string> = {
          reliability: 'HealthScoreReliability',
          limits: 'HealthScoreLimits',
          security: 'HealthScoreSecurity',
          tests: 'HealthScoreTests',
          debt: 'HealthScoreDebt',
        };
        for (const [subKey, metricName] of Object.entries(subScoreMetricNames)) {
          const subScore = (healthScore.subScores as any)[subKey];
          if (typeof subScore === 'number') {
            summaryMetrics[metricName] = subScore;
          }
        }
        healthScoreDetails = healthScore.details;
        uxLog("action", this, c.cyan(t('monitoringHealthScoreComputed', { score: c.bold(healthScore.score) })));
        for (const detail of healthScore.details) {
          uxLog("log", this, c.grey(detail));
        }
      }
    }

    // Always send the consolidated summary notification: it doubles as a daily heartbeat
    // for observability backends (freshness panels and "silent org" alerts key on it)
    try {
      const summaryText = aiSummary
        ? `${t('monitoringAiSummaryNotifTitle', { orgUrl })}\n\n${aiSummary}`
        : t('monitoringSummaryNotifText', {
          orgUrl,
          success: commandsSummary.filter((cmd) => cmd.status === 'success').length,
          failed: summaryMetrics.CommandsFailed,
        });

      // Severity drives the routing: the AI executive summary is worth a user-facing
      // message (info reaches messaging/email defaults), while the plain daily heartbeat
      // only matters to observability backends (log reaches the api channel only)
      const summaryNotif: any = {
        text: summaryText,
        type: 'MONITORING_SUMMARY' as const,
        severity: (aiSummary ? 'info' : 'log') as 'info' | 'log',
        logElements: [],
        metrics: summaryMetrics,
        data: Object.assign(
          { notificationCount: notifications.length },
          healthScoreDetails ? { healthScoreDetails } : {}
        ),
      };

      // Send consolidated summary notification
      await NotifProvider.postNotifications(summaryNotif);
    } catch (summaryErr) {
      uxLog("warning", this, c.yellow(t('monitoringAiSummaryFailed', { message: (summaryErr as Error).message })));
    }

    delete process.env.MONITORING_NOTIF_OUTPUT_DIR;

    // Exit code is 1 if monitoring detected stuff
    if (success === false) {
      process.exitCode = 1;
    }
    return { outputString: 'Monitoring processed on org ' + orgUrl };
  }
}
