{
 "title": "DASH - 00_Home",
 "tags": [
  "sfdx-hardis",
  "salesforce",
  "monitoring"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org",
    "label": "Salesforce Org",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Org Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{type=\"ORG_LIMITS\", orgIdentifier=\"$org\", source=\"sfdx-hardis\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Data Storage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ORG_LIMITS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "File Storage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ORG_LIMITS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Daily Api Requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ORG_LIMITS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Daily Bulk API",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ORG_LIMITS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Daily Platform Events",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ORG_LIMITS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  { "title": "User Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Weekly CRM Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ACTIVE_USERS_CRM_WEEKLY\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Monthly Portal Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ACTIVE_USERS_EXPERIENCE_MONTHLY\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Inactive CRM Users (6 months)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"UNUSED_USERS_CRM_6_MONTHS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Inactive Portal Users (6 months)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"UNUSED_USERS_EXPERIENCE_6_MONTHS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  { "title": "Org Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Updated Metadatas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"BACKUP\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Suspiscious Updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"AUDIT_TRAIL\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Apex Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"APEX_ERROR\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Flow Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"FLOW_ERROR\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Legacy API Calls",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"LEGACY_API\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  { "title": "Apex Tests & Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Failing tests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"APEX_TESTS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Apex Code Coverage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"APEX_TESTS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Unsecured Connected Apps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"UNSECURED_CONNECTED_APPS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Security Health Check",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ORG_HEALTH_CHECK\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  { "title": "Org Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Release Updates to check",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"RELEASE_UPDATES\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "SF Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ORG_INFO\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Org Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ORG_INFO\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Next Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ORG_INFO\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Next Upgrade",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"ORG_INFO\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  { "title": "Technical Debt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Deactivated Flows & VRs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"METADATA_STATUS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Unused Connected Apps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"CONNECTED_APPS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Unused Apex Classes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"UNUSED_APEX_CLASSES\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Attributes without permissions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"LINT_ACCESS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Unused Metadatas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"UNUSED_METADATAS\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Fields without Description",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"MISSING_ATTRIBUTES\", orgIdentifier=\"$org\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  { "title": "Licenses & Packages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{orgIdentifier=\"$org\", type=\"LICENSES\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "{orgIdentifier=\"$org\", type=\"LICENSES\"} |= ``",
     "maxLines": 1
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{orgIdentifier=\"$org\", type=\"BACKUP\"} |= ``",
     "maxLines": 1
    }
   ]
  }
 ]
}