---
# Pipeline pour tester la qualité du code Apex / Aura / LWC d'un repository

# Liste ordonnée des étapes du pipeline
stages:
  - check # Controle de qualité des sources

# On execute les jobs sur l'image hardisgroupcom/sfdx-hardis qui contient les applications necessaires
# Version latest recommandée, cependant beta et alpha peuvent être utilisées pour les tests
image: hardisgroupcom/sfdx-hardis:latest

# Variables globales aux jobs
variables:
  FORCE_COLOR: "1"

# Controle de la qualité des sources avec Mega-Linter, qui contient sfdx-scanner (apex PMD),
# mais aussi d'autres linters et détecteurs de mauvaises pratiques
check_quality:
  stage: check
  tags:
    - ubuntu
  only:
    - merge_requests
    - web
  image: oxsecurity/megalinter-salesforce:latest
  script: ["true"]
  variables:
    # All available variables are described in documentation
    # https://megalinter.io/latest/config-file/
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    DEFAULT_BRANCH: master
  artifacts:
    when: always
    paths:
      - megalinter-reports
    expire_in: 1 week
