/*
sfdx-hardis is managed in 3 layers, wit hthe following priority
- project, stored in /config
- branches, stored in /config/branches
- user, stored in /config/users

getConfig(layer) returns:
- project + branches + user if layer is user
- project + branches if layer is branch
- project if layer is project
*/

import { Connection, SfError } from '@salesforce/core';
import { httpGet } from '../common/utils/httpUtils.js';
import c from 'chalk';
import { cosmiconfig } from 'cosmiconfig';
import fs from '../common/utils/fsUtils.js';
import * as yaml from 'js-yaml';
import * as os from 'os';
import * as path from 'path';
import { getCurrentGitBranch, isCI, isGitRepo, uxLog } from '../common/utils/index.js';
import { prompts } from '../common/utils/prompts.js';
import { t } from '../common/utils/i18n.js';

const moduleName = 'sfdx-hardis';
const projectConfigFiles = [
  'package.json',
  `.${moduleName}.yaml`,
  `.${moduleName}.yml`,
  `config/.${moduleName}.yaml`,
  `config/.${moduleName}.yml`,
];
const username = os.userInfo().username;
const userConfigFiles = [`config/user/.${moduleName}.${username}.yaml`, `config/user/.${moduleName}.${username}.yml`];
const REMOTE_CONFIGS: any = {};

import { CONSTANTS } from './constants.js';
export { CONSTANTS };

export const getApiVersion = (conn: Connection | null = null) => {
  // globalThis.currentOrgApiVersion is set during authentication check (so not set if --skipauth option is used)
  return process.env.SFDX_API_VERSION || globalThis.currentOrgApiVersion || (conn ? conn.getApiVersion() || CONSTANTS.DEFAULT_API_VERSION : CONSTANTS.DEFAULT_API_VERSION);
}

export const getApiVersionNumber = (conn: Connection | null = null) => {
  const apiVersion = getApiVersion(conn);
  return parseFloat(apiVersion);
}

export const getBannerMarkdownAndLink = () => {
  if (CONSTANTS.BANNER_IMAGE_URL === false) {
    return '';
  }
  return `[![${t('bannerImageAltText')}](${CONSTANTS.BANNER_IMAGE_URL})](${CONSTANTS.WEBSITE_URL})`;
}

// Banner displayed at the top of a Pull Request comment: a Pull Request can carry a deployment check
// comment, a deployment comment and a deployment actions comment at the same time, and they all look
// alike once scrolled past. One image per type and status makes them recognizable at a glance.
// Images are generated by scripts/generate-pr-banners.mjs
export type PrCommentBannerKey =
  | 'validation-success'
  | 'validation-failure'
  | 'deployment-success'
  | 'deployment-failure'
  | 'actions-completed'
  | 'actions-pending'
  | 'actions-error';

// Validation and deployment comments are only posted once completed, so they carry no pending
// banner: their only statuses are success and failure. Only the deployment actions comment has a
// pending state (manual actions still waiting to be performed).
const PR_COMMENT_BANNERS: Record<PrCommentBannerKey, { file: string; altTextKey: string }> = {
  'validation-success': { file: 'pr-banner-validation-success.png', altTextKey: 'prBannerValidationSuccess' },
  'validation-failure': { file: 'pr-banner-validation-failure.png', altTextKey: 'prBannerValidationFailure' },
  'deployment-success': { file: 'pr-banner-deployment-success.png', altTextKey: 'prBannerDeploymentSuccess' },
  'deployment-failure': { file: 'pr-banner-deployment-failure.png', altTextKey: 'prBannerDeploymentFailure' },
  'actions-completed': { file: 'pr-banner-actions-completed.png', altTextKey: 'prBannerActionsCompleted' },
  'actions-pending': { file: 'pr-banner-actions-pending.png', altTextKey: 'prBannerActionsPending' },
  'actions-error': { file: 'pr-banner-actions-error.png', altTextKey: 'prBannerActionsError' },
};

/**
 * Markdown of the banner image of a Pull Request comment, followed by a blank line.
 * The alt text is displayed only when the image is hidden or cannot be loaded: pass the comment
 * title as altText so the banner can replace the title heading without losing it.
 * Returns an empty string when there is no banner for the key, or when banners are disabled with
 * SFDX_HARDIS_PR_COMMENT_BANNERS=false (useful when a network blocks raw.githubusercontent.com).
 */
export const getPrCommentBannerMarkdown = (bannerKey: PrCommentBannerKey | null | undefined, altText?: string): string => {
  if (!bannerKey || (getEnvVar('SFDX_HARDIS_PR_COMMENT_BANNERS') || '') === 'false') {
    return '';
  }
  const banner = PR_COMMENT_BANNERS[bannerKey];
  if (!banner) {
    return '';
  }
  return `![${altText || t(banner.altTextKey)}](${CONSTANTS.PR_COMMENT_BANNER_BASE_URL}${banner.file})\n\n`;
}

async function getBranchConfigFiles() {
  if (!isGitRepo()) {
    return [];
  }
  const gitBranchFormatted = process.env.CONFIG_BRANCH || (await getCurrentGitBranch({ formatted: true }));
  const branchConfigFiles = [
    `config/branches/.${moduleName}.${gitBranchFormatted}.yaml`,
    `config/branches/.${moduleName}.${gitBranchFormatted}.yml`,
  ];
  return branchConfigFiles;
}

const promptTemplateCache: Record<string, any> = {};

export const getConfig = async (layer: "project" | "branch" | "user" = 'user', options: { cache: boolean } = { cache: false }): Promise<any> => {
  if (options.cache && promptTemplateCache[layer]) {
    return promptTemplateCache[layer];
  }
  const defaultConfig = await loadFromConfigFile(projectConfigFiles);
  if (layer === 'project') {
    promptTemplateCache['project'] = defaultConfig;
    return defaultConfig;
  }
  let branchConfig = await loadFromConfigFile(await getBranchConfigFiles());
  branchConfig = Object.assign(defaultConfig, branchConfig);
  if (layer === 'branch') {
    promptTemplateCache['branch'] = branchConfig;
    return branchConfig;
  }
  let userConfig = await loadFromConfigFile(userConfigFiles);
  userConfig = Object.assign(branchConfig, userConfig);
  promptTemplateCache['user'] = userConfig;
  return userConfig;
};

// Set data in configuration file
export const setConfig = async (layer: string, propValues: any): Promise<string | void> => {
  if (layer === 'user' && (fs.readdirSync(process.cwd()).length === 0 || !isGitRepo())) {
    if (process?.argv?.includes('--debug')) {
      uxLog("log", this, c.grey(t('skippingUpdateOfUserConfigFileBecause')));
    }
    return;
  }
  const configSearchPlaces =
    layer === 'project'
      ? projectConfigFiles
      : layer === 'user'
        ? userConfigFiles
        : layer === 'branch'
          ? await getBranchConfigFiles()
          : [];
  return await setInConfigFile(configSearchPlaces, propValues);
};

// Load configuration from file
async function loadFromConfigFile(searchPlaces: string[]): Promise<any> {
  try {
    const configExplorer = await cosmiconfig(moduleName, {
      searchPlaces,
    }).search();
    let config = configExplorer != null ? configExplorer.config : {};
    if (config.extends) {
      const remoteConfig = await loadFromRemoteConfigFile(config.extends);
      config = Object.assign(remoteConfig, config);
    }
    return config;
  } catch (err) {
    uxLog("error", this, c.red('[sfdx-hardis] Unable to read configuration file.\n' + (err as Error).message));
    throw new SfError(
      '[sfdx-hardis] Unable to read configuration file.\n' + (err as Error).message
    );
  }
}

async function loadFromRemoteConfigFile(url) {
  if (REMOTE_CONFIGS[url]) {
    return REMOTE_CONFIGS[url];
  }
  const remoteConfigResp = await httpGet(url, { responseType: 'text' });
  if (remoteConfigResp.status !== 200) {
    throw new SfError(
      '[sfdx-hardis] Unable to read remote configuration file at ' + url + '\n' + JSON.stringify(remoteConfigResp)
    );
  }
  const remoteConfig = yaml.load(remoteConfigResp.data);
  REMOTE_CONFIGS[url] = remoteConfig;
  return remoteConfig;
}

// Update configuration file
export async function setInConfigFile(searchPlaces: string[], propValues: any, configFile: string = '') {
  let explorer;
  if (configFile === '') {
    explorer = cosmiconfig(moduleName, { searchPlaces });
    const configExplorer = await explorer.search();
    configFile = configExplorer != null ? configExplorer.filepath : searchPlaces.slice(-1)[0];
  }
  let doc: any = {};
  if (fs.existsSync(configFile)) {
    doc = yaml.load(fs.readFileSync(configFile, 'utf-8'));
  }
  doc = Object.assign(doc, propValues);
  await fs.ensureDir(path.dirname(configFile));
  await fs.writeFile(configFile, yaml.dump(doc));
  if (explorer) {
    explorer.clearCaches();
  }
  // A created or updated branch config file changes the major orgs list: drop its cache.
  // Dynamic import: orgConfigUtils depends on modules that depend on this config module.
  if (configFile.replace(/\\/g, '/').includes('config/branches/')) {
    const { clearListMajorOrgsCache } = await import('../common/utils/orgConfigUtils.js');
    clearListMajorOrgsCache();
  }
  if (!isCI) {
    uxLog(
      "other",
      this,
      c.magentaBright(`Updated config file ${c.bold(configFile)} with values: \n${JSON.stringify(propValues, null, 2)}`)
    );
  }
  return configFile;
}

// Check configuration of project so it works with sfdx-hardis
export const checkConfig = async (options: any) => {
  // Skip hooks from other commands than hardis:scratch commands
  const commandId = options?.Command?.id || options?.id || '';
  if (!commandId.startsWith('hardis')) {
    return;
  }

  let devHubAliasOk = false;
  // Check projectName is set. If not, request user to input it
  if (
    options.Command &&
    (options.Command.requiresProject === true ||
      options.Command.supportsDevhubUsername === true ||
      options?.flags?.devhub === true ||
      options.devHub === true)
  ) {
    const configProject = await getConfig('project');
    let projectName = process.env.PROJECT_NAME || configProject.projectName;
    devHubAliasOk = (process.env.DEVHUB_ALIAS || configProject.devHubAlias) != null;
    // If not found, prompt user project name and store it in user config file
    if (projectName == null) {
      projectName = await promptForProjectName();
      await setConfig('project', {
        projectName,
        devHubAlias: `DevHub_${projectName}`,
      });
      devHubAliasOk = true;
    }
  }

  // Set DevHub username if not set
  if (devHubAliasOk === false && options.Command && options.Command.supportsDevhubUsername === true) {
    const configProject = await getConfig('project');
    const devHubAlias = process.env.DEVHUB_ALIAS || configProject.devHubAlias;
    if (devHubAlias == null) {
      await setConfig('project', {
        devHubAlias: `DevHub_${configProject.projectName}`,
      });
    }
  }
};

export async function getReportDirectory() {
  const configProject = await getConfig('project');
  const defaultReportDir = path.join(process.cwd(), 'hardis-report');
  const reportDir = configProject.reportDirectory || defaultReportDir;
  await fs.ensureDir(reportDir);
  return reportDir;
}

export function getEnvVar(envVarName: string): string | null {
  const varValue = process.env[envVarName] || null;
  // Avoid Azure cases that sends the expression as string if variable not defined
  // RegEx will match on strings beginning with '$(' some text, then ')' 
  // It will match unresolved environment vars e.g. $(System.PullRequest.PullRequestId) or $(JIRA_TICKET_REGEX)
  if (varValue && /^\$\([^)]+\)$/.test(varValue)) {
    return null;
  }
  return varValue;
}

export function getCurrentI18nLocale(): string {
  return (process.env.SFDX_HARDIS_LANG || process.env.SFDX_HARDIS_LOCALE || 'en')
    .substring(0, 5)
    .replace(/^([a-zA-Z]{2})(-?)([a-zA-Z]{0,2})$/, (_match, p1, p2, p3) =>
      p1.toLowerCase() + p2 + p3.toUpperCase()
    );
}

export function getLocalizedEnvVar(baseName: string): string | null {
  const locale = getCurrentI18nLocale();
  const localeSuffix = locale.replace(/-/g, '_').toUpperCase();
  return getEnvVar(`${baseName}_${localeSuffix}`) || getEnvVar(baseName);
}

export function getEnvVarList(envVarName: string, separator: string = ','): string[] | null {
  const varValue = getEnvVar(envVarName);
  if (varValue) {
    return varValue.split(separator).map((item) => item.trim());
  }
  return null;
}

export async function promptForProjectName() {
  const projectRes = await prompts({
    type: 'text',
    name: 'projectName',
    message: t('whatIsTheNameOfYourProject'),
    description: t('usedToGenerateEnvironmentVariablesAndConfig'),
    placeholder: t('exMyClient'),
  });
  const userProjectName = projectRes.projectName + '';
  let projectName = projectRes.projectName.toLowerCase().replace(' ', '_');
  // Make sure that projectName is compliant with the format of an environment variable
  projectName = projectName.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[^a-zA-Z_]+/, '');
  if (projectName !== userProjectName) {
    uxLog(
      "action",
      this,
      c.cyan(
        t('projectNameHasBeenChanged', { projectName })
      )
    );
    const promptResp = await prompts({
      type: 'confirm',
      message: t('areYouOkWithUpdatedProjectName', { projectName }),
      description: t('confirmsUseOfSanitizedProjectName'),
    });
    if (promptResp.value === true) {
      return projectName;
    }
    return promptForProjectName();
  }
  return projectName;
}
