import { getConfig } from '../../config/index.js';
import { prompts } from './prompts.js';
import c from 'chalk';
import fs from './fsUtils.js';
import * as path from "path";
import sortArray from './sortArray.js';
import { SfError, SfProject } from '@salesforce/core';
import {
  arrayUniqueByKey,
  arrayUniqueByKeys,
  execCommand,
  execSfdxJson,
  extractRegexMatches,
  getCurrentGitBranch,
  getGitRepoRoot,
  getGitRepoUrl,
  git,
  gitFetch,
  uxLog,
} from './index.js';
import { CommonPullRequestInfo, GitProvider } from '../gitProvider/index.js';
import { Ticket, TicketProvider } from '../ticketProvider/index.js';
import { getTicketCollectionIssues } from '../ticketProvider/ticketProviderRoot.js';
import { DefaultLogFields, ListLogLine } from 'simple-git';
import { flowDiffToMarkdownForPullRequest } from '../gitProvider/utilsMarkdown.js';
import { MessageAttachment } from '@slack/types';
import { getBranchMarkdown, getNotificationButtons, getOrgMarkdown } from './notifUtils.js';
import { NotifProvider, UtilsNotifs } from '../notifProvider/index.js';
import { setConnectionVariables } from './orgUtils.js';
import { WebSocketClient } from '../websocketClient.js';
import { countPackageXmlItems } from './xmlUtils.js';
import type { DeploymentMetrics } from './deployUtils.js';
import { t, tMaybe } from './i18n.js';
import { buildDeploymentActionsAttachmentText } from './deploymentActionsRegistry.js';
import { isComponentChangeDetailComplete } from './deployResultSummary.js';
import { getEnvVar } from '../../config/index.js';

// Builds a commit message following the Conventional Commits v1.0.0 specification
// (https://www.conventionalcommits.org/en/v1.0.0/), so commits generated by sfdx-hardis
// pass commitlint with the default @commitlint/config-conventional rules:
// - header "type(scope): subject" limited to 100 characters
// - subject starting in lowercase, without trailing period
// - body separated from the header by a blank line, with lines wrapped at 100 characters
export function buildConventionalCommitMessage(options: {
  type?: string;
  scope?: string | null;
  subject: string;
  body?: string;
}): string {
  const type = options.type || 'chore';
  const scope = options.scope === undefined ? 'sfdx-hardis' : options.scope;
  let subject = (options.subject || '').replace(/\s+/g, ' ').trim();
  subject = subject.charAt(0).toLowerCase() + subject.slice(1);
  let header = (scope ? `${type}(${scope}): ` : `${type}: `) + subject;
  if (header.length > 100) {
    header = header.substring(0, 100);
  }
  header = header.trimEnd().replace(/\.+$/, '');
  if (!options.body) {
    return header;
  }
  const wrappedBody = options.body
    .split('\n')
    .flatMap((line) => wrapCommitBodyLine(line, 100))
    .join('\n');
  return header + '\n\n' + wrappedBody;
}

// Wraps a single line at word boundaries so it never exceeds maxLength characters
function wrapCommitBodyLine(line: string, maxLength: number): string[] {
  if (line.length <= maxLength) {
    return [line];
  }
  const wrapped: string[] = [];
  let current = '';
  for (const word of line.split(' ')) {
    if (current === '') {
      current = word;
    } else if (current.length + 1 + word.length <= maxLength) {
      current += ' ' + word;
    } else {
      wrapped.push(current);
      current = word;
    }
    // Hard-split words longer than maxLength (e.g. long URLs)
    while (current.length > maxLength) {
      wrapped.push(current.substring(0, maxLength));
      current = current.substring(maxLength);
    }
  }
  if (current !== '') {
    wrapped.push(current);
  }
  return wrapped;
}

function getDefaultBranchLabel(branchName: string): string {
  const lower = branchName.toLowerCase();
  if (lower === 'integration' || lower === 'integ') {
    return t('defaultLabelBuildStream');
  }
  if (lower === 'preprod' || lower === 'uatrun' || lower === 'uat_run') {
    return t('defaultLabelRunStream');
  }
  if (lower === 'main' || lower === 'production') {
    return t('defaultLabelHotfixStream');
  }
  return '';
}

// Priority: explicit label array > comma-embedded label > default by branch name
function resolveBranchLabel(branchRaw: string, configBranchLabels: string[], idx: number): string {
  if (idx >= 0 && configBranchLabels[idx]) {
    return configBranchLabels[idx];
  }
  if (branchRaw.includes(',')) {
    return branchRaw.split(',').slice(1).join(',').trim();
  }
  return getDefaultBranchLabel(branchRaw);
}

export function buildAvailableTargetBranches(config: any): { branches: string[]; display: string[] } {
  const configBranches: string[] = Array.isArray(config.availableTargetBranches) ? config.availableTargetBranches : [];
  const configBranchLabels: string[] = config.availableTargetBranchesLabels || [];
  const branches = [
    ...configBranches,
    ...(config.developmentBranch ? [config.developmentBranch] : []),
  ].filter((value: string, index: number, self: string[]) => value && self.indexOf(value) === index);
  const display = branches.map((branch) => {
    const branchValue = branch.includes(',') ? branch.split(',')[0] : branch;
    const idx = configBranches.indexOf(branch);
    const label = resolveBranchLabel(branch, configBranchLabels, idx);
    return label ? `${branchValue} (${label})` : branchValue;
  });
  return { branches, display };
}

export async function selectTargetBranch(options: { message?: string } = {}) {
  const gitUrl = await getGitRepoUrl() || '';
  const message =
    options.message ||
    t('whatWillBeTheTargetBranch', { mergeRequestName: GitProvider.getMergeRequestName(gitUrl) });
  const config = await getConfig('user');
  const availableTargetBranches = config.availableTargetBranches || null;
  const availableTargetBranchesLabels: string[] = config.availableTargetBranchesLabels || [];
  // There is only once choice so return it
  if (availableTargetBranches === null && config.developmentBranch) {
    uxLog("action", this, c.cyan(t('automaticallySelectedTargetBranchIs', { config: c.green(config.developmentBranch) })));
    return config.developmentBranch;
  }

  // Request info to build branch name. ex features/config/MYTASK
  const response = await prompts([
    {
      type: availableTargetBranches ? 'select' : 'text',
      name: 'targetBranch',
      message: c.cyanBright(message),
      description: t('descChooseTargetBranch'),
      placeholder: availableTargetBranches ? undefined : t('exIntegration'),
      choices: availableTargetBranches
        ? availableTargetBranches.map((branch, index) => {
          const branchValue = branch.includes(',') ? branch.split(',')[0] : branch;
          const label = resolveBranchLabel(branch, availableTargetBranchesLabels, index);
          return {
            title: branchValue,
            description: label || undefined,
            value: branchValue,
          };
        })
        : [],
      initial: config.developmentBranch || 'integration',
    },
  ]);
  const targetBranch = response.targetBranch || 'integration';
  return targetBranch;
}

export async function getGitDeltaScope(currentBranch: string, targetBranch: string) {
  // Ref used to compute the delta against the target branch. Defaults to the local <target> ref.
  let targetRef = targetBranch;
  try {
    await gitFetch(['origin', `${targetBranch}:${targetBranch}`]);
  } catch (e) {
    uxLog(
      "other",
      this,
      `[Warning] Unable to fetch target branch ${targetBranch} to prepare call to sfdx-git-delta\n` +
      JSON.stringify(e)
    );
    // Fallback (e.g. when the target branch is checked out in another git worktree, so the local
    // ref cannot be updated): refresh the remote-tracking ref and compute the delta against origin/<target>.
    try {
      await gitFetch(['origin', targetBranch]);
      targetRef = `origin/${targetBranch}`;
    } catch (e2) {
      uxLog(
        "other",
        this,
        `[Warning] Unable to fetch origin/${targetBranch} to prepare call to sfdx-git-delta\n` +
        JSON.stringify(e2)
      );
    }
  }
  try {
    await gitFetch(['origin', `${currentBranch}:${currentBranch}`]);
  } catch (e) {
    uxLog(
      "other",
      this,
      `[Warning] Unable to fetch current branch ${currentBranch} to prepare call to sfdx-git-delta\n` +
      JSON.stringify(e)
    );
  }
  const logResult = await git().log([`${targetRef}..${currentBranch}`]);
  const toCommit = logResult.latest;
  const mergeBaseCommand = `git merge-base ${targetRef} ${currentBranch}`;
  const mergeBaseCommandResult = await execCommand(mergeBaseCommand, this, {
    fail: true,
  });
  const masterBranchLatestCommit = mergeBaseCommandResult.stdout.replace('\n', '').replace('\r', '');
  return { fromCommit: masterBranchLatestCommit, toCommit: toCommit, logResult: logResult };
}

async function getPackageDirectoriesFromProject(gitRoot: string): Promise<string[] | null> {
  const sfdxProjectFile = path.join(gitRoot, 'sfdx-project.json');
  if (!await fs.pathExists(sfdxProjectFile)) {
    return null;
  }
  try {
    const project = await SfProject.resolve(gitRoot);
    const packageDirs = project.getPackageDirectories();
    if (!packageDirs || packageDirs.length === 0) {
      return null;
    }
    // Validate that all package directories exist
    for (const dir of packageDirs) {
      if (!await fs.pathExists(dir.fullPath)) {
        throw new Error(
          `Package directory "${dir.path}" defined in sfdx-project.json does not exist at ${dir.fullPath}`
        );
      }
    }
    // Extract relative paths from package directory objects
    return packageDirs.map((dir) => dir.path);
  } catch (error) {
    if (error instanceof Error && error.message.includes('Package directory')) {
      throw error;
    }
    // Log other parsing errors but continue
    uxLog("other", this, `sfdx-project.json found but could not be parsed: ${error}`);
    return null;
  }
}

export async function callSfdxGitDelta(from: string, to: string, outputDir: string, options: any = {}) {
  const gitRoot = await getGitRepoRoot();
  let packageXmlGitDeltaCommand = `sf sgd:source:delta --from "${from}" --to "${to}" --output ${outputDir} --ignore-whitespace`;

  // Check for sfdx-project.json and apply packageDirectories filtering
  const packageDirs = await getPackageDirectoriesFromProject(gitRoot);
  if (packageDirs === null) {
    uxLog("other", this, 'sfdx-project.json not found, processing all delta changes');
  } else if (packageDirs.length > 0) {
    // Add --source-dir flag for each package directory
    packageDirs.forEach((dir) => {
      packageXmlGitDeltaCommand += ` --source-dir ${dir}`;
    });
  }

  const gitDeltaCommandRes = await execSfdxJson(packageXmlGitDeltaCommand, this, {
    output: true,
    fail: false,
    debug: options?.debugMode || false,
    cwd: gitRoot,
  });
  // Fail here rather than later: when sfdx-git-delta does not run, the caller reads the delta
  // package.xml it was supposed to write and dies on a file-not-found that says nothing about
  // the real cause. Report what sfdx-git-delta actually answered instead.
  if (gitDeltaCommandRes?.status && gitDeltaCommandRes.status !== 0) {
    // A --json command that fails reports its output in errorMessage, not in stdout/stderr
    const sgdOutput = (
      gitDeltaCommandRes?.errorMessage ||
      `${gitDeltaCommandRes?.stdout || ''}${gitDeltaCommandRes?.stderr || ''}` ||
      gitDeltaCommandRes?.message ||
      ''
    ).trim();
    throw new SfError(
      `[DeltaDeployment] sfdx-git-delta failed (status ${gitDeltaCommandRes.status}).\n` +
      `Command: ${packageXmlGitDeltaCommand}\n` +
      `Working directory: ${gitRoot}\n` +
      `Output: ${sgdOutput || '(none)'}`
    );
  }
  // Send results to UI if there is one (skip if caller handles notifications)
  if (WebSocketClient.isAliveWithLwcUI() && !options?.skipWebSocketNotification) {
    const deltaPackageXml = path.join(outputDir, 'package', 'package.xml');
    const deltaPackageXmlExists = await fs.exists(deltaPackageXml);
    if (deltaPackageXmlExists) {
      const deltaNumberOfItems = await countPackageXmlItems(deltaPackageXml);
      if (deltaNumberOfItems > 0) {
        WebSocketClient.sendReportFileMessage(deltaPackageXml, t('gitDeltaPackageXmlCount', { count: deltaNumberOfItems }), "report");
      }
    }
    const deltaDestructiveChangesXml = path.join(outputDir, 'destructiveChanges', 'destructiveChanges.xml');
    const deltaDestructiveChangesXmlExists = await fs.exists(deltaDestructiveChangesXml);
    if (deltaDestructiveChangesXmlExists) {
      const deltaDestructiveChangesNumberOfItems = await countPackageXmlItems(deltaDestructiveChangesXml);
      if (deltaDestructiveChangesNumberOfItems > 0) {
        WebSocketClient.sendReportFileMessage(deltaDestructiveChangesXml, t('gitDeltaDestructiveChangesXmlCount', { count: deltaDestructiveChangesNumberOfItems }), "report");
      }
    }
  }
  return gitDeltaCommandRes;
}

export function getPullRequestData(): any {
  return globalThis.pullRequestData || {};
}

export function setPullRequestData(prData: any): void {
  globalThis.pullRequestData = Object.assign(globalThis.pullRequestData || {}, prData);
}

export async function computeCommitsSummary(checkOnly, pullRequestInfo: CommonPullRequestInfo | null = null) {
  uxLog("action", this, c.cyan(t('computingCommitsSummary')));
  const currentGitBranch = await getCurrentGitBranch();
  let logResults: (DefaultLogFields & ListLogLine)[] = [];
  let previousTargetBranchCommit = "";
  if (checkOnly || GitProvider.isDeployBeforeMerge()) {
    const prInfo = await GitProvider.getPullRequestInfo({ useCache: true });
    const deltaScope = await getGitDeltaScope(
      prInfo?.sourceBranch || currentGitBranch || "",
      prInfo?.targetBranch || process.env.FORCE_TARGET_BRANCH || ""
    );
    logResults = [...deltaScope.logResult.all];
    previousTargetBranchCommit = deltaScope.fromCommit;
  } else {
    const logRes = await git().log([`HEAD^..HEAD`]);
    previousTargetBranchCommit = "HEAD^"
    logResults = [...logRes.all];
  }
  logResults = arrayUniqueByKeys(logResults, ['message', 'body']).reverse();
  // LEGACY: free-text "MANUAL ACTION:" markers typed in commit messages / Pull Request bodies.
  // Superseded by deployment actions of type "manual" (commandsPreDeploy / commandsPostDeploy),
  // which carry an id, a phase, instructions and a tracked per-org status.
  // See https://sfdx-hardis.cloudity.com/salesforce-ci-cd-work-on-task-deployment-actions/
  // Kept for projects that still rely on it; notifications nudge users towards deployment actions.
  const manualActions: any[] = [];
  const tickets: Ticket[] = [];
  let commitsList = '';
  let displayedCommitsCount = 0;
  const maxCommitBodyChars = 400;
  for (const logResult of logResults) {
    // Tickets and manual actions are collected from EVERY commit, including the plumbing merge
    // commits filtered out of the displayed list below.
    await collectTicketsAndManualActions(
      currentGitBranch + '\n' + logResult.message + (logResult.body ? '\n' + logResult.body : ''),
      tickets,
      manualActions,
      {
        commits: [logResult],
      }
    );
    // Plumbing merge commits ("Merge branch 'x' into y", "Merge pull request #12 from ...")
    // carry no user-readable information
    if (/^Merge (pull request #|branch |remote-tracking branch )/.test(logResult.message)) {
      continue;
    }
    displayedCommitsCount++;
    // Commit text is user-written: raw HTML (a </details>, an unclosed <!-- ...) would break out
    // of the <details> wrapper below and could swallow the rest of the Pull Request comment
    commitsList += '**' + logResult.message.replace(/</g, '&lt;') + '**, by ' + logResult.author_name;
    if (logResult.body) {
      // Long bodies (pasted release notes...) flood the comment: keep the beginning only
      let bodyDisplay = logResult.body;
      let truncated = false;
      if (bodyDisplay.length > maxCommitBodyChars) {
        bodyDisplay = bodyDisplay.substring(0, maxCommitBodyChars);
        truncated = true;
      }
      bodyDisplay = bodyDisplay.replace(/</g, '&lt;');
      // Close an unbalanced code fence (from the body itself or cut open by the truncation),
      // so the rest of the comment stays intact
      if ((bodyDisplay.match(/```/g) || []).length % 2 === 1) {
        bodyDisplay += '\n```\n';
      }
      if (truncated) {
        bodyDisplay += '... *(truncated)*';
      }
      commitsList += '<br/>' + bodyDisplay + '\n\n';
    } else {
      commitsList += '\n\n';
    }
  }
  // Collapsed by default: the commit list is the longest and least actionable section of the comment
  let commitsSummary = '## Commits summary\n\n';
  if (displayedCommitsCount === 0) {
    commitsSummary += '_No user commits in this scope (technical merge commits only)._\n\n';
  } else {
    commitsSummary += `<details>\n<summary>${displayedCommitsCount} commit(s)</summary>\n\n${commitsList}\n</details>\n\n`;
  }

  // Tickets and references can also be in PR description
  if (pullRequestInfo) {
    const prText = (pullRequestInfo.title || '') + (pullRequestInfo.description || '');
    await collectTicketsAndManualActions(currentGitBranch + '\n' + prText, tickets, manualActions, {
      pullRequestInfo: pullRequestInfo,
    });
  }

  // Unify and sort tickets
  const ticketsSorted: Ticket[] = sortArray(arrayUniqueByKey(tickets, 'id'), { by: ['id'], order: ['asc'] });
  uxLog("log", this, c.grey('[TicketProvider] ' + t('ticketProviderFoundTickets', { count: ticketsSorted.length })));
  // Try to contact Ticketing servers to gather more info
  await TicketProvider.collectTicketsInfo(ticketsSorted);

  // Add manual actions in markdown
  const manualActionsSorted = [...new Set(manualActions)].reverse();
  if (manualActionsSorted.length > 0) {
    let manualActionsMarkdown = '## Manual actions\n\n';
    for (const manualAction of manualActionsSorted) {
      manualActionsMarkdown += '- ' + manualAction + '\n';
    }
    commitsSummary = manualActionsMarkdown + '\n\n' + commitsSummary;
  }

  // Add tickets in markdown
  if (ticketsSorted.length > 0) {
    let ticketsMarkdown = '## Tickets\n\n';
    for (const ticket of ticketsSorted) {
      if (ticket.foundOnServer) {
        ticketsMarkdown += '- [' + ticket.id + '](' + ticket.url + ') ' + ticket.subject;
        if (ticket.statusLabel) {
          ticketsMarkdown += ' (' + ticket.statusLabel + ')';
        }
        ticketsMarkdown += '\n'
      } else {
        ticketsMarkdown += '- [' + ticket.id + '](' + ticket.url + ')\n';
      }
    }
    // When the ticketing server could not be reached (expired token...), say it in the comment
    // instead of silently listing bare links
    const ticketCollectionIssues = getTicketCollectionIssues();
    if (ticketCollectionIssues.length > 0) {
      ticketsMarkdown += `\n> ⚠️ ${ticketCollectionIssues[0]}\n`;
    }
    commitsSummary = ticketsMarkdown + '\n\n' + commitsSummary;
  }

  // Add Flow diff in Markdown
  let flowDiffMarkdown: any = {};
  if ((checkOnly || GitProvider.isDeployBeforeMerge()) && !(process.env?.SFDX_DISABLE_FLOW_DIFF === "true")) {
    const flowList: string[] = [];
    for (const logResult of logResults) {
      const updatedFiles = await getCommitUpdatedFiles(logResult.hash);
      for (const updatedFile of updatedFiles) {
        if (updatedFile.endsWith(".flow-meta.xml")) {
          if (fs.existsSync(updatedFile)) {
            const flowName = path.basename(updatedFile, ".flow-meta.xml");
            flowList.push(flowName);
          }
          else {
            uxLog("warning", this, c.yellow(`[FlowGitDiff] Unable to find Flow file ${updatedFile} (probably has been deleted)`));
          }
        }
      }
    }
    const flowListUnique = [...new Set(flowList)].sort();
    // Truncate flows to the only 30 ones, to avoid flooding the pull request comments
    let truncatedNb = 0;
    const maxFlowsToShow = parseInt(process.env?.MAX_FLOW_DIFF_TO_SHOW || "30");
    if (flowListUnique.length > maxFlowsToShow) {
      truncatedNb = flowListUnique.length - maxFlowsToShow;
      flowListUnique.splice(maxFlowsToShow, flowListUnique.length - maxFlowsToShow);
      uxLog("warning", this, c.yellow(`[FlowGitDiff] Truncated flow list to 30 flows to avoid flooding Pull Request comments`));
      uxLog("warning", this, c.yellow(`[FlowGitDiff] If you want to see the diff of truncated flows, use the VS Code SFDX Hardis extension 😊`));
    }
    flowDiffMarkdown = await flowDiffToMarkdownForPullRequest(flowListUnique, previousTargetBranchCommit, (logResults.at(-1) || logResults[0]).hash, truncatedNb);
  }

  return {
    markdown: commitsSummary,
    logResults: logResults,
    manualActions: manualActionsSorted,
    tickets: ticketsSorted,
    flowDiffMarkdown: flowDiffMarkdown
  };
}

async function collectTicketsAndManualActions(str: string, tickets: Ticket[], manualActions: any[], options: any) {
  const foundTickets = await TicketProvider.getProvidersTicketsFromString(str, options);
  tickets.push(...foundTickets);
  // LEGACY mechanism, see the comment on `manualActions` in computeCommitsSummary.
  // Extract manual actions if defined
  const manualActionsRegex = /MANUAL ACTION:(.*)/gm;
  const manualActionsMatches = await extractRegexMatches(manualActionsRegex, str);
  manualActions.push(...manualActionsMatches);
}

export async function getCommitUpdatedFiles(commitHash) {
  const result = await git().show(["--name-only", "--pretty=format:", commitHash]);
  // Split the result into lines (file paths) and remove empty lines
  const files = result.split('\n').filter(file => file.trim() !== '' && fs.existsSync(file));
  return files;
}

export async function buildCheckDeployCommitSummary() {
  try {
    const pullRequestInfo = await GitProvider.getPullRequestInfo({ useCache: true });
    const commitsSummary = await computeCommitsSummary(true, pullRequestInfo);
    const prDataCommitsSummary = {
      commitsSummary: commitsSummary.markdown,
      flowDiffMarkdown: commitsSummary.flowDiffMarkdown
    };
    setPullRequestData(prDataCommitsSummary);
  } catch (e3) {
    uxLog("warning", this, c.yellow(t('unableToComputeGitSummary') + e3));
  }
}

/**
 * Deployment notifications are posted to shared team channels, often read by people in several
 * countries, so they stay in English by default whatever SFDX_HARDIS_LANG says on the machine
 * running the pipeline. Set notifTranslateDeploymentMessages in .sfdx-hardis.yml, or the
 * NOTIF_TRANSLATE_DEPLOYMENT_MESSAGES env var, to follow the configured locale instead.
 */
export async function isDeploymentNotifTranslationEnabled(): Promise<boolean> {
  const envVarValue = getEnvVar('NOTIF_TRANSLATE_DEPLOYMENT_MESSAGES');
  if (envVarValue !== null && envVarValue !== undefined && `${envVarValue}` !== '') {
    return `${envVarValue}` === 'true';
  }
  const config = await getConfig('branch');
  return config?.notifTranslateDeploymentMessages === true;
}

export async function handlePostDeploymentNotifications(flags, targetUsername: any, quickDeploy: any, delta: boolean, debugMode: boolean, additionalMessage = "", deploymentMetrics: DeploymentMetrics | null = null) {
  const pullRequestInfo = await GitProvider.getPullRequestInfo({ useCache: true });
  const translateNotif = await isDeploymentNotifTranslationEnabled();
  // Only report the split when it accounts for every deployed component (see the predicate)
  const changeDetailComplete = isComponentChangeDetailComplete(deploymentMetrics);
  const deploymentActionsText = buildDeploymentActionsAttachmentText(translateNotif, {
    deployExecuted: (deploymentMetrics?.componentsDeployed ?? 0) > 0 || (deploymentMetrics?.componentsTotal ?? 0) > 0,
    componentsDeployed: deploymentMetrics?.componentsDeployed ?? 0,
    componentsDeleted: deploymentMetrics?.componentsDeleted ?? 0,
    componentsChangeDetail: changeDetailComplete,
    componentsCreated: deploymentMetrics?.componentsCreated ?? 0,
    componentsUpdated: deploymentMetrics?.componentsUpdated ?? 0,
    componentsUnchanged: deploymentMetrics?.componentsUnchanged ?? 0,
  });
  // Collected separately from the deployment actions so the section order below is guaranteed even
  // when computing the commits summary fails.
  let commitAttachments: CommitNotifAttachments = {};
  try {
    // Build notification attachments & handle ticketing systems comments
    const collected = await collectNotifAttachments(pullRequestInfo, translateNotif);
    commitAttachments = collected.attachments;
    await TicketProvider.postDeploymentActions(
      collected.commitsSummary.tickets,
      flags['target-org']?.getConnection()?.instanceUrl || targetUsername || '',
      pullRequestInfo
    );
  } catch (e4: any) {
    uxLog(
      "warning",
      this,
      c.yellow('Unable to handle commit info on TicketProvider post deployment actions:\n' + e4.message) +
      '\n' +
      c.gray(e4.stack)
    );
  }

  // Section order: tickets, deployment actions, manual actions, commits.
  // Commits stay last because the size guard trims from the last attachment backwards, and the
  // commit list is both the longest and the least actionable section.
  const attachments: MessageAttachment[] = [
    commitAttachments.tickets,
    deploymentActionsText ? { text: deploymentActionsText } : undefined,
    commitAttachments.manualActions,
    commitAttachments.commits,
  ].filter((attachment): attachment is MessageAttachment => attachment !== undefined);

  const orgMarkdown = await getOrgMarkdown(
    flags['target-org']?.getConnection()?.instanceUrl || targetUsername || ''
  );
  const branchMarkdown = await getBranchMarkdown();
  let notifMessage = `Deployment has been successfully processed from branch ${branchMarkdown} to org ${orgMarkdown}`;
  notifMessage += quickDeploy
    ? ' (🚀 quick deployment)'
    : delta
      ? ' (🌙 delta deployment)'
      : ' (🌕 full deployment)';
  if (additionalMessage) {
    notifMessage += '\n\n' + additionalMessage + "\n\n"
  }

  const notifButtons = await getNotificationButtons();
  if (pullRequestInfo) {
    if (debugMode) {
      uxLog("error", this, c.grey(t('prInfo') + JSON.stringify(pullRequestInfo)));
    }
    const prAuthor = pullRequestInfo?.authorName;
    notifMessage += `\nRelated: <${pullRequestInfo.webUrl}|${pullRequestInfo.title}>` + (prAuthor ? ` by ${prAuthor}` : '');
    const prButtonText = 'View Pull Request';
    notifButtons.push({ text: prButtonText, url: pullRequestInfo.webUrl });
  } else {
    uxLog("warning", this, c.yellow("WARNING: Unable to get Pull Request info, notif won't have a button URL"));
  }
  await setConnectionVariables(flags['target-org']?.getConnection(), true);// Required for some notifications providers like Email
  await NotifProvider.postNotifications({
    type: 'DEPLOYMENT',
    text: notifMessage,
    buttons: notifButtons,
    pullRequestUrl: pullRequestInfo?.webUrl,
    translateMessages: translateNotif,
    severity: 'success',
    attachments: attachments,
    logElements: [],
    data: { metric: deploymentMetrics?.componentsDeployed ?? 0 },
    metrics: {
      DeployedItems: deploymentMetrics?.componentsDeployed ?? 0,
      // The five impact counters travel together, and only when the deploy results carried
      // per-component detail for every deployed component: an absent metric means "not measured",
      // while a 0 would claim the deployment changed nothing in the org. Emitting the deleted
      // count alone would also leave the dashboard's stacked chart with a single zeroed series.
      ...(changeDetailComplete
        ? {
          DeploymentComponentsCreated: deploymentMetrics?.componentsCreated ?? 0,
          DeploymentComponentsUpdated: deploymentMetrics?.componentsUpdated ?? 0,
          DeploymentComponentsDeleted: deploymentMetrics?.componentsDeleted ?? 0,
          DeploymentComponentsChanged:
            (deploymentMetrics?.componentsCreated ?? 0) +
            (deploymentMetrics?.componentsUpdated ?? 0) +
            (deploymentMetrics?.componentsDeleted ?? 0),
          DeploymentComponentsUnchanged: deploymentMetrics?.componentsUnchanged ?? 0,
        }
        : {}),
      DeploymentComponentsTotal: deploymentMetrics?.componentsTotal ?? 0,
      DeploymentComponentsFailed: deploymentMetrics?.componentsFailed ?? 0,
      DeploymentTestsRun: deploymentMetrics?.testsRun ?? 0,
      DeploymentTestsFailed: deploymentMetrics?.testsFailed ?? 0,
      DeploymentTestsTotal: deploymentMetrics?.testsTotal ?? 0,
      DeploymentCodeCoverage: deploymentMetrics?.codeCoveragePercent ?? 0,
      DeploymentDurationSeconds: deploymentMetrics?.durationSeconds ?? 0,
      DeploymentQuickDeploy: deploymentMetrics?.quickDeploy ? 1 : 0,
      DeploymentDelta: deploymentMetrics?.delta ? 1 : 0,
      DeploymentSuccess: deploymentMetrics?.success === false ? 0 : 1,
    },
  });
}


interface CommitNotifAttachments {
  tickets?: MessageAttachment;
  manualActions?: MessageAttachment;
  commits?: MessageAttachment;
}

// Returns the attachments as named slots rather than a flat array, so the caller decides the
// section order and can interleave the deployment actions section.
async function collectNotifAttachments(pullRequestInfo: CommonPullRequestInfo | null, translate: boolean) {
  const attachments: CommitNotifAttachments = {};
  const commitsSummary = await computeCommitsSummary(false, pullRequestInfo);
  // Tickets attachment
  if (commitsSummary.tickets.length > 0) {
    attachments.tickets = ({
      text: `**${tMaybe(translate, 'notifAttachmentTickets')}**\n${commitsSummary.tickets
        .map((ticket) => {
          if (ticket.foundOnServer) {
            let ticketsMarkdown = '- ' + UtilsNotifs.markdownLink(ticket.url, ticket.id) + ' ' + ticket.subject;
            if (ticket.statusLabel) {
              ticketsMarkdown += ' (' + ticket.statusLabel + ')';
            }
            return ticketsMarkdown;
          } else {
            return '- ' + UtilsNotifs.markdownLink(ticket.url, ticket.id);
          }
        })
        .join('\n')}`,
    });
  }
  // Manual actions attachment (LEGACY "MANUAL ACTION:" commit markers)
  if (commitsSummary.manualActions.length > 0) {
    attachments.manualActions = ({
      text: `**${tMaybe(translate, 'notifAttachmentManualActions')}**\n${commitsSummary.manualActions
        .map((manualAction) => {
          return '- ' + manualAction;
        })
        .join('\n')}` +
        // Nudge towards deployment actions, which track a status instead of being free text.
        `\n\n_${tMaybe(translate, 'notifManualActionsLegacyHint')}_`,
    });
  }
  // Commits attachment
  if (commitsSummary.logResults.length > 0) {
    attachments.commits = ({
      text: `**${tMaybe(translate, 'notifAttachmentCommits')}**\n${commitsSummary.logResults
        .map((logResult) => {
          return '- ' + tMaybe(translate, 'notifCommitByAuthor', { message: logResult.message, author: logResult.author_name });
        })
        .join('\n')}`,
    });
  }
  return { commitsSummary, attachments };
}

export function makeFileNameGitCompliant(fileName: string) {
  // Remove all characters that are not alphanumeric, underscore, hyphen, space or dot
  const sanitizedFileName = fileName.replace(/[^a-zA-Z0-9_. -]/g, '_');
  return sanitizedFileName;
}

export function getFileAtCommit(commit: string, filePath: string) {
  return git().show([`${commit}:${filePath}`]);
}