name: "DOC - Build and deploy with sfdx-hardis"
on:
  push:
    branches:
      - main
      - doc

jobs:
  # Build & deploy docs
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Build doc with sfdx-hardis
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn prepack
      - run: npm i @salesforce/cli -g
      - run: echo y|sfdx plugins:install sfdx-hardis
      - run: sfdx hardis:doc:plugin:generate
      # Deploy docs with mkdocs-material
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mdx_truly_sane_lists json-schema-for-humans mkdocs-glightbox==0.3.2 pymdown-extensions==9.1
      - run: mkdocs gh-deploy --force

  git-sync:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "hardisgroupcom/sfdx-hardis"
          source_branch: "gh-pages"
          destination_repo: "git@github.com:sfdx-hardis/sfdx-hardis.github.io.git"
          destination_branch: "gh-pages"
          # ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          # source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.SFDX_HARDIS_GITHUB_IO_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
