---
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: "Build & Deploy - ALPHA"
on:
  push:
    branches:
      - "docker"

###############
# Set the Job #
###############
jobs:
  push_alpha_to_registry:
    name: Push alpha Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
    environment:
      name: alpha
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker Image (Latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            SFDX_HARDIS_VERSION=latest
            SFDX_CLI_VERSION=latest
          load: false
          push: true
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: |
            docker.io/hardisgroupcom/sfdx-hardis:latest
            ghcr.io/hardisgroupcom/sfdx-hardis:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/hardisgroupcom/sfdx-hardis:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          security-checks: vuln
          severity: "CRITICAL,HIGH"
